### ISSUE TITLE
Distribution via conda-forge 

### ISSUE THREAD

**Issue by janniklasrose** [chebpy/chebpy#20]
Since `pip install chebpy` is already taken by a [different chebpy project](https://pypi.org/project/chebpy/), it would be good to have a different distribution channel that stills allows the end user to install in a simple memorable command.

It's pretty easy to add a package to [conda forge](https://conda-forge.org/#add_recipe) (I think last time it took me a handful of commits and a day of waiting to get it approved), and afterwards it's as easy as

`conda install -c conda-forge chebpy`

## TODOs
- [x] Repository name
  - See #26 
- [x] Version number
  - conda-forge requires a version number. `setup.py` currently has `0.1.0`, but perhaps you want to make a new one given the recent significant changes.
- [x] Tag & Release
  - conda-forge requires a [release](https://github.com/chebpy/chebpy/releases) `.tar.gz` archive file with `sha256` sum.

**Comment by markrichardson** [comment]
definitely. and a good reason to begin a semantic versioning discipline

**Comment by janniklasrose** [comment]
I've made a start on the conda-forge [recipe](https://github.com/janniklasrose/staged-recipes/blob/chebpy/recipes/chebpy/meta.yaml).

Before submitting it, the chebpy repo needs a few changes (see the above **TODOs** checklist).

**Comment by janniklasrose** [comment]
@markrichardson Are you okay with being listed as recipe maintainer, too? I'm supposed to warn that it comes with a bit of spam from conda-forge.

**Comment by markrichardson** [comment]
no problem, thanks

**Comment by markrichardson** [comment]
Ok, I've just tagged v0.1.0, then updated setup.py to v0.2.0 and created a corresponding v0.2.0 tag

**Comment by janniklasrose** [comment]
Great! I will make a pull request to conda-forge today.

**Comment by janniklasrose** [comment]
@markrichardson can you add a comment to the [PR](https://github.com/conda-forge/staged-recipes/pull/12729) confirming you want to be included as maintainer?

**Comment by markrichardson** [comment]
done, thanks

**Comment by markrichardson** [comment]
nice work. I just tested it and added to https://github.com/chebpy/chebpy/blob/master/INSTALL.rst
