### ISSUE TITLE
first example doesn't work

### ISSUE THREAD

**Issue by keithbriggs** [chebpy/chebpy#3]
kbriggs:~> python2
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
>>> from chebpy import chebfun
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name chebfun
>>> import chebpy 
>>> x=chebpy.chebfun('x',(0,20))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'chebfun'

>>> chebpy.__dict__.keys()
['cheb_mde_split', 'cheb_mde_etdrk4', 'cheb_D1_fft', 'interpolation_1d', 'misc', 'EPS', 'clencurt_weights', '__path__', 'cheb', 'cheb_mde_neumann_split', 'cheb_interpolation_point', 'complex_contour_integral', 'cheb_allen_cahn_etdrk4', 'cheb_D1_dct', 'barycentric_matrix', 'cheb_inverse_fast_transform', 'barycentric_weights_cgl', 'almost_equal', '__package__', 'cheb_mde_robin_etdrk4', 'cheb_interpolation_2d', 'cheb_D1_fchebt', '__version__', '__doc__', 'cheb_quadrature_cgl', 'chebt', 'chebq', 'cheb_polynomial_series', '__license__', '__builtins__', 'barycentric_weights_cg', '__file__', '__author__', 'barycentric_weights', 'cheba', '__name__', 'etdrk4_coeff_ndiag', 'interpolation_2d', 'chebi', 'cheb_barycentric_matrix', 'cheb_polynomial_trigonometric', 'integral', 'clencurt_weights_fft', 'chebd', 'cheb_fast_transform', 'interpolation_point', 'cheb_polynomial_recursion', 'cheb_quadrature_clencurt', 'cheb_D1_mat', 'cheb_interpolation_1d', 'cheb_mde_neumann_etdrk4']

**Comment by markrichardson** [comment]
Keith - it looks to me as though there may be a package conflict here. I'm guessing that the printout above is due to you having installed https://pypi.python.org/pypi/chebpy? (Totally separate package from this one.) Maybe try "pip uninstall chebpy" first and try again?

**Comment by keithbriggs** [comment]
Mark: thanks - yes, I installed your package from sources, and it worked.  I had no idea that pip could install a different package of the same name without warning me!

Keith

________________________________

**Comment by markrichardson** [comment]
Thanks Keith, glad it's working now. Agree it's not ideal there's already a package on PyPi with the same name. Do let me know as you get on and feel free to open other threads as appropriate.

**Comment by keithbriggs** [comment]
Will do - thanks for your help!

K

________________________________
