### ISSUE TITLE
expm2, expm3 removed from scipy.linalg

### ISSUE THREAD

**Issue by jwuttke** [chebpy/chebpy#36]
chebpy/cheba.py (as per pip3) imports expm2, expm3. These functions are no longer part of scipy.linalg.

**Comment by markrichardson** [comment]
hi @jwuttke. I think you are using a different chebpy package (https://pypi.org/project/chebpy/). confusingly it has the same name. 

Can you try installing per here: https://github.com/chebpy/chebpy/blob/master/INSTALL.rst

**Comment by jwuttke** [comment]
Thanks for the clarification, and sorry for my spurious issues.
