### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by janniklasrose** [chebpy/chebpy#47]
[Type hints](https://www.python.org/dev/peps/pep-0484/) would make maintaining and developing for ChebPy easier. They were introduced in Python 3.5, so this would not break support (provided that some of the new language features are not used yet).

**Comment by markrichardson** [comment]
Agree, this will make a big difference.

**Comment by janniklasrose** [comment]
Using this issue to discuss something else with you: how do you feel about an automatic source code formatter/linter?

The common choices for Python are
- [black](https://github.com/psf/black) (by design very opinionated, with [few customisation options](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file)) and
- [flake8](https://flake8.pycqa.org/en/latest/) (which does not do any formatting but checks for PEP 8 compliance, and has the option to exclude certain violations via [extensive customisation](https://flake8.pycqa.org/en/latest/user/configuration.html)).

Both are easy to integrate in the CI workflow that we have to ensure code quality stays high over time.

**Comment by markrichardson** [comment]
I think this makes sense to get in place. Do you have a preference out of these two?

**Comment by janniklasrose** [comment]
I like that black auto-formats and doesn't just check compliance. Would probably go with it, because pushes can be auto-formatted via CI to avoid contributors/developers having to install and **remember** to run black.

Just applied it to `master` and results look mostly fine. For specific sections where a different non-black style is sought, the tool supports
`# fmt: on/off` fences.

**Comment by markrichardson** [comment]
I'm not familiar with either but reading through it seemed to me that some black's minor (though hopefully not overbearing) enforcement is probably the way to go. Happy to trial this out on a branch and see what we think?

On developers remembering to do things: I wonder if we should put together a guide / checklist of things to take care of when contributing / submitting a PR. By the same token we should probably do the same thing for ourselves for (say) version tags as there are now more moving parts than there were. (Things like remembering to update the version number in __init__.py).

**Comment by markrichardson** [comment]
(Opened #55 & #56 for checklists)

**Comment by janniklasrose** [comment]
Yes, good idea! Especially to ensure the same version is deployed to both conda-forge and PyPI. A few notes:

- conda-forge uses the autotick bot that monitors the GitHub release (based on a tag) to ship the new version. 
- For PyPI we (will) use a GitHub Action triggered by a tag to build and push to PyPI. This requires the version in `__init__.py` to be the correct new version.

Thus a new version requires the following:
- [ ] All checks of the most up-to-date commit on `master` should pass. This concerns the merge commit after a PR or something directly pushed to `master` (although PRs are definitely preferred even for us).
- [ ] A new commit is made that increments the `__version__` inside `chebpy/__init__.py` **AND** (optionally) bumps the version in the `launch binder` badge in `README.rst`.
- [ ] That commit is tagged to create a release of that version
- [ ] Ensure a new automatic PR on `chebfun-feedstock` is created
- [ ] Ensure CD workflow for pushing to PyPI happens and succeeds.

**Comment by janniklasrose** [comment]
Moved my comment over to https://github.com/chebpy/chebpy/issues/56#issuecomment-956138170
