### ISSUE TITLE
matplotlib <2 dependency causes problems in Py 3

### ISSUE THREAD

**Issue by jamadagni** [chebpy/chebpy#5]
Hello. I cloned and installed `chebpy` on my Kubuntu Bionic LTS system.

I don't myself directly use Py 2, so I installed **chebpy** using `sudo python3 setup.py install`. It pulled in MatPlotLib 1.5.3 from PyPI and installed it under `/usr/local/lib/python3.6/dist-packages/` while MPL 2.1.1 is under `/usr/lib/python3/dist-packages/` from the regular `python3-matplotlib` Ubuntu package.

But then when I try to use MPL from within Py 3:

```python3
import matplotlib.pyplot as plt
import numpy as np

# Data for plotting
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

# Note that using plt.subplots below is equivalent to using
# fig = plt.figure and then ax = fig.add_subplot(111)
fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()
plt.show()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-fab32e28ac5d> in <module>
     14        title='About as simple as it gets, folks')
     15 ax.grid()
---> 16 plt.show()

/usr/local/lib/python3.6/dist-packages/matplotlib-1.5.3-py3.6-linux-x86_64.egg/matplotlib/pyplot.py in show(*args, **kw)
    250     """
    251     global _show
--> 252     return _show(*args, **kw)
    253 
    254 

/usr/local/lib/python3.6/dist-packages/ipykernel/pylab/backend_inline.py in show(close, block)
     37             display(
     38                 figure_manager.canvas.figure,
---> 39                 metadata=_fetch_figure_metadata(figure_manager.canvas.figure)
     40             )
     41     finally:

/usr/local/lib/python3.6/dist-packages/ipykernel/pylab/backend_inline.py in _fetch_figure_metadata(fig)
    172     """Get some metadata to help with displaying a figure."""
    173     # determine if a background is needed for legibility
--> 174     if _is_transparent(fig.get_facecolor()):
    175         # the background is transparent
    176         ticksLight = _is_light([label.get_color()

/usr/local/lib/python3.6/dist-packages/ipykernel/pylab/backend_inline.py in _is_transparent(color)
    193 def _is_transparent(color):
    194     """Determine transparency from alpha."""
--> 195     rgba = colors.to_rgba(color)
    196     return rgba[3] < .5

AttributeError: module 'matplotlib.colors' has no attribute 'to_rgba'
```

Doing `pip3 uninstall matplotlib` removed the PyPI MPL 1.5 leaving my Ubuntu MPL 2.1 intact, and I am able to use MPL 2.1 as to plot the output of ChebPy.

Strictly speaking MPL cannot be a “requirement” of ChebPy because the role of ChebPy is only to construct chebyshev approximations to other functions. Whether the user wants to plot it or use it elsewhere is a different matter. In Debian packaging terminology, MPL would only be a “Recommends” for ChebPy and not a “Depends”.

Nevertheless, it remains that ChebPy pulls in an inappropriate version of MPL under Py 3 at least. Further examining the cause, I find a strange thing:

https://github.com/chebpy/chebpy/blob/a32051163c8bf58e3fb9c2ee7d7d4b6ff9e02bca/setup.py#L18

https://github.com/chebpy/chebpy/blob/a32051163c8bf58e3fb9c2ee7d7d4b6ff9e02bca/requirements.txt#L2

I don't know what the `requirements.txt` does but it seems to be ineffective and the version given by `setup.py` is pulled in causing the problem.

Please look into this. Thank you!

**Comment by markrichardson** [comment]
Thanks for flagging the issue. I've pushed a provisional fix into the master branch which I hope should get you on your way. This has only been tested on Python 3.6. It's possible that this now may cause issues for Python 2 users instead. But probably better to have that balance this way around. 

Fair comments on plotting. Currently matplotlib is a de-facto dependency in the sense that the library will fail to run without it. But your point is that it doesn't have to be like this. I'm happy to look at setting things up in the way your hinting at, but this would require some re-factoring -- only adding the object.plot() methods in the case where the user has matplotlib. If you are keen to have a go, please!

**Comment by janniklasrose** [comment]
Had a go at implementing this (#11) but only tested this with and without Python 3 in Anaconda.
